/*this file is generated by OpenJava system.*/

public final class BinarySearchOJMI
{
public static final String[][] dict={
 {"instantiates","GeneticAlgorithm.InstrumentCode.BranchInstrumentor"}
};
}
