/*
 * This code was generated by ojc.
 */
import GeneticAlgorithm.InstrumentCode.*;
import java.util.*;


public class MyInt
{

    private int number;

    public MyInt()
    {
        trace.add( new java.lang.Integer( 1 ) );
        number = 1;
    }

    public MyInt( int number )
    {
        trace.add( new java.lang.Integer( 2 ) );
        this.number = number;
    }

    public int getNumber()
    {
        trace.add( new java.lang.Integer( 3 ) );
        return number;
    }

    public void setNumber( int number )
    {
        trace.add( new java.lang.Integer( 4 ) );
        this.number = number;
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
