/*
 * This code was generated by ojc.
 */
import GeneticAlgorithm.InstrumentCode.*;
import java.util.*;


public class Point
{

    int x;

    int y;

    public Point()
    {
        trace.add( new java.lang.Integer( 1 ) );
    }

    public Point( int x, int y )
    {
        trace.add( new java.lang.Integer( 2 ) );
        this.x = x;
        this.y = y;
    }

    public int getX()
    {
        trace.add( new java.lang.Integer( 3 ) );
        return x;
    }

    public void setX( int x )
    {
        trace.add( new java.lang.Integer( 4 ) );
        this.x = x;
    }

    public int getY()
    {
        trace.add( new java.lang.Integer( 5 ) );
        return y;
    }

    public void setY( int y )
    {
        trace.add( new java.lang.Integer( 6 ) );
        this.y = y;
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
